WIP
Spacelocust/for-democracy pull request #28
Opened 2024-05-20 21:09 UTC by LeoBruant

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Closes #9

## Type of change

Please add any relevant information to the type of change you've made.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update (or is a documentation update)
-   [ ] HIGH IMPORTANCE (requires a fast merging)

## Has This Been Tested?

Please describe the tests that you ran to verify your changes. It is way more likely for a PR to be merged and approved with successful tests.

-   [x] Yes, I ran tests
-   [ ] No, I did not include any test
-   [ ] No test is needed for this change

2024-05-28 16:10 UTC, Spacelocust commented on mobile/lib/widgets/event/detail.dart
> +                onTap: () {},
```suggestion
```

2024-05-28 18:47 UTC, YummYume requested changes

2024-05-28 18:47 UTC, YummYume commented on compose.yml
> +  # Uncomment to use Flutter
Mettre dans le README à la place

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/main.dart
> -        useMaterial3: true,
Remettre ?

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/main.dart
> +          // background: ThemeColors.surface,
```suggestion
```

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +          } else if (snapshot.hasError) {
```suggestion
          }
          
          if (snapshot.hasError || !snapshot.hasData) {
```

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +          } else {
Retirer le else

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +            }
```suggestion
```

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +            final events = snapshot.data;
```suggestion
            final events = snapshot.data!;
```

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +                          style: Theme.of(context).textTheme.headlineLarge),
```suggestion
                      title: Text('Ongoing defenses',
                          style: Theme.of(context).textTheme.headlineLarge,),
```

+ Traduction

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +                        title: Text(defence.planet?.name ?? ''),
```suggestion
                        title: Text(defence.planet.name),
```

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +                        title: Text(liberation.planet?.name ?? ''),
```suggestion
                        title: Text(liberation.planet.name),
```

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/screens/events_screen.dart
> +                          style: Theme.of(context).textTheme.headlineLarge),
Pareil

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/widgets/event/detail.dart
> +              const Text('Some text'),
Mettre un TODO si pas terminé ?

2024-05-28 18:47 UTC, YummYume commented on mobile/lib/widgets/event/detail.dart
> +                      // color: Colors.blue,
```suggestion
```

2024-06-01 18:51 UTC, YummYume approved these changes

2024-06-01 18:51 UTC, merged