Feature/auth
Spacelocust/for-democracy pull request #30
Opened 2024-05-26 01:33 UTC by Spacelocust

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #(issue) | No issue linked.

## Type of change

Please add any relevant information to the type of change you've made.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update (or is a documentation update)
-   [ ] HIGH IMPORTANCE (requires a fast merging)

## Has This Been Tested?

Please describe the tests that you ran to verify your changes. It is way more likely for a PR to be merged and approved with successful tests.

-   [x] Yes, I ran tests
-   [ ] No, I did not include any test
-   [ ] No test is needed for this change

2024-05-28 19:04 UTC, YummYume requested changes

2024-05-28 19:04 UTC, YummYume commented on api/internal/oauth/config.go
> +var baseUrl = "http://10.0.2.2:5000"
Retirer ?

2024-05-28 19:04 UTC, YummYume commented on api/internal/server/oauth.go
> +		<title>Centered Image</title>
```suggestion
		<title>For Democracy - Login</title>
		<meta name="robots" content="noindex, nofollow">
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/l10n/app_en.arb
> +  "@@locale": "en",
Remettre comme avant sinon on va avoir des conflits inutiles

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/screens/web_oauth_screen.dart
> +class WebOauthScreen extends StatefulWidget {
```suggestion
class WebOAuthScreen extends StatefulWidget {
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/screens/web_oauth_screen.dart
> +class _WebOauthScreenState extends State<WebOauthScreen> {
```suggestion
class _WebOAuthScreenState extends State<WebOauthScreen> {
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/screens/web_oauth_screen.dart
> +  String steamCallbackUrl = '/oauth/steam/callback';
const ?

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/screens/web_oauth_screen.dart
> +            }
On comprend pas trop

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/screens/web_oauth_screen.dart
> +        orElse: () => Cookie(name, ""));
```suggestion
        orElse: () => Cookie(name, ""),);
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/services/api_service.dart
> +              e.response!.statusMessage!.contains('token invalid')) {
Un peu bizarre de vérifier un message

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/services/oauth_service.dart
> +  static const String oauthUrl = '/oauth/me';
```suggestion
abstract class OAuthService {
  static const String oAuthUrl = '/oauth/me';
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/components/square_avatar.dart
> +  final double size;
Espacement

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/components/square_avatar.dart
> +        ));
```suggestion
  const SquareAvatar(
      {super.key, required this.avatar, this.size = 40, this.onTap,});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        onTap: onTap,
        child: DecoratedBox(
          decoration: BoxDecoration(
            image: DecorationImage(
              image: avatar.image,
            ),
            borderRadius: BorderRadius.circular(5.0),
          ),
          child: SizedBox(width: size, height: size),
        ),);
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/layout/main_navigation_drawer.dart
> +    }
```suggestion
    }
    
    return Container();
```

On est sûr de vouloir mettre un container vide ?

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/layout/main_navigation_drawer.dart
> +          ));
```suggestion
          ),);
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/layout/main_navigation_drawer.dart
> +    } else {
```suggestion
    }
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/layout/main_navigation_drawer.dart
> +              )));
```suggestion
              ),),);
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/layout/main_scaffold.dart
> +    } else {
```suggestion
    }
```

2024-05-28 19:04 UTC, YummYume commented on mobile/lib/widgets/layout/main_scaffold.dart
> +          child: Icon(Icons.account_circle));
```suggestion
          child: Icon(Icons.account_circle),);
```

2024-05-28 19:04 UTC, YummYume commented on mobile/pubspec.yaml
> +    - assets/
ça include tout automatiquement ?

2024-05-28 19:13 UTC, Spacelocust commented on mobile/pubspec.yaml
> +    - assets/
Ouaip

2024-05-28 19:15 UTC, Spacelocust commented on mobile/lib/screens/web_oauth_screen.dart
> +            }
Je vais essayer d'améliorer et de commenter

2024-05-28 19:17 UTC, Spacelocust commented on mobile/lib/services/api_service.dart
> +              e.response!.statusMessage!.contains('token invalid')) {
Je n'ai pas réellement d'autres moyens

2024-05-28 19:20 UTC, Spacelocust commented on mobile/lib/widgets/layout/main_navigation_drawer.dart
> +    }
J'aurais préféré mettre rien ou un Widget qui fait office de vide

2024-05-29 08:40 UTC, YummYume approved these changes

2024-05-29 08:40 UTC, YummYume commented on api/internal/server/oauth.go
> +		<title>For Democracy - Login</title>
```suggestion
		<title>For Democracy - Login</title>
		<meta name="robots" content="noindex, nofollow">
```

2024-05-29 09:17 UTC, merged