Fix : Some fixes
Spacelocust/for-democracy pull request #57
Opened 2024-07-14 17:18 UTC by LeoBruant

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Closes #(issue) | No issue linked.

## Type of change

Please add any relevant information to the type of change you've made.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update (or is a documentation update)
-   [ ] HIGH IMPORTANCE (requires a fast merging)

## Has This Been Tested?

Please describe the tests that you ran to verify your changes. It is way more likely for a PR to be merged and approved with successful tests.

-   [x] Yes, I ran tests
-   [ ] No, I did not include any test
-   [ ] No test is needed for this change

2024-07-14 18:15 UTC, Spacelocust requested changes

2024-07-14 18:15 UTC, Spacelocust commented on web/lib/models/feature.dart
> +  @JsonKey(required: true, name: 'code')
```suggestion
  @JsonKey(required: true, name: 'Code')
```

2024-07-14 18:15 UTC, Spacelocust commented on web/lib/models/feature.dart
> +  @JsonKey(required: true, name: 'active')
```suggestion
  @JsonKey(required: true, name: 'Enabled')
```

2024-07-18 13:43 UTC, YummYume approved these changes

2024-07-18 13:44 UTC, Spacelocust approved these changes

2024-07-18 13:45 UTC, merged